### ISSUE TITLE
setState after unmount

### ISSUE THREAD

**Issue by ronag** [sergiodxa/react-lazy-image#1]
`setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Image component.`

Should probably check if the component is unmounted when doing asynchronous setState.

**Comment by sergiodxa** [comment]
Interesting, in fact the download should be aborted if the component is unmounted before it ends, I'm going to fix this today.

**Comment by sergiodxa** [comment]
I changed the `componenWillUnmount` to call `.abort()` on the request, this should avoid the `setState` on unmounted components.
