### ISSUE TITLE
How to set defaultSource prop for custom loader?

### ISSUE THREAD

**Issue by vitthalr** [sergiodxa/react-lazy-image#10]
I saw your comment on one issue: - 

> The defaultSource prop is used for that. Is documented on the readme.

But I'm not clear how to define defaultSource, can you please throw some light on it?

Thank you very much in advance.

Much appreciated!!

**Comment by sergiodxa** [comment]
Pass it as a prop with that name and send a URL to an image or an inlined image as base64.
