### ISSUE TITLE
Listing react as a peerDependency instead of dependency

### ISSUE THREAD

**Issue by Erigers** [sergiodxa/react-lazy-image#11]
Hi there,
I've used your package in a project and it seems to fail the image loading, enter in the onError callback with this error:
`this.updater.enqueueCallback is not a function`
even though the image exists. 
I've been looking around for the cases this error was thrown and this react issue thread explains that the package installation brings an older version than react since it's listed as a `dependency` not as a `peerDependency`: 
https://github.com/facebook/react/issues/10320#issuecomment-332353869
Please, can you apply this quick fix ?

**Comment by sergiodxa** [comment]
React is already a peerDependency

https://github.com/sergiodxa/react-lazy-image/blob/master/package.json#L29

**Comment by Erigers** [comment]
<img width="241" alt="screen shot 2018-02-15 at 8 25 32 pm" src="https://user-images.githubusercontent.com/11444502/36276627-d4106e4a-128e-11e8-8b2b-cb899bc37d7e.png">
When I install react-lazy-image via npm, this is what I see in `node_modules/react-lazy-image/package.json`. Is this how it's supposed to  be?
