### ISSUE TITLE
Internet Explorer Support

### ISSUE THREAD

**Issue by ashleydb** [sergiodxa/react-lazy-image#7]
Related to #1 , in IE11 this error is shown in componentWillUnmount.

```
SCRIPT5007: Unable to get property 'abort' of undefined or null reference
```

Seems like this.request is null.

**Comment by ashleydb** [comment]
I can only think this is being caused because of an earlier error:

```
Unhandled promise rejection InvalidStateError
```

**Comment by sergiodxa** [comment]
I personally don't support IE (any version), but if you now how to fix it PR are welcomed :)
