### ISSUE TITLE
XHR Loading causes CORS issues

### ISSUE THREAD

**Issue by zachary95** [sergiodxa/react-lazy-image#8]
Hello,

Using this package causes CORS issues because of XHR requests for non-configured servers. This can be tricky when trying to load images from server where we don't have access to change CORS policy.

However with a 5 mins investigation : The `Image()` object can load images and bypass CORS validation. But it load it into a `HTMLImageElement` thus making it harder to inject with React (maybe with refs?). Plus I don't know if we can keep loading cancelation.

**Comment by manelet** [comment]
I had to stop using it coz of this. 😔

**Comment by zachary95** [comment]
I've ended up by rewritting CORS policies. But at the end, the API was loading images from sources out of our control (yeah, it's bad but MVP has reasons that logic ignores) so I've dropped any lazy load support since.

**Comment by manelet** [comment]
I'm about to do the same 😅

**Comment by eshwarenm** [comment]
me too :(
